Algoritmo "area_perimetro"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Adonias Pires
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Cintia Dias
// Data atual  : 26/08/2019
Var

perimetro, area, raio: real

Inicio
Escreva ("Digite o valor do raio: ")
leia(raio)

area <- PI*raio^2
perimetro<- 2*PI*raio

Escreva ("O valor do seu perimetro é ", perimetro, " e o valor da sua area é:  ",area)


Fimalgoritmo