Algoritmo "Total_vendas"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Adonias Pires
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Cintia Dias
// Data atual  : 26/08/2019
Var

total_vendas:real

Inicio
Escreva ("Digite o total de vendas: ")
leia(total_vendas)

total_vendas<-total_vendas * 10/100

Escreva ( "A comissao do vendedor é R$ ",total_vendas)


Fimalgoritmo