Algoritmo "área_triangulo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : ADONIAS PIRES
// Descrição   : Ler e imprimir a area de triangulo
// Autor(a)    : Cintia dias
// Data atual  : 26/08/2019
Var
area: real
altura, base: inteiro

Inicio
Escreva("Digite a base: ")
leia (base)
Escreva ("Digite a altura: ")
leia(altura)

area<- (base * altura)/2

Escreva ("A area de um triangulo é: ", area)


Fimalgoritmo